-

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspbian
    - role: ubuntu

- hosts: master
  become: yes
  vars:
    extra_server_args: "--disable servicelb"
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node
