---
- name: Check whether boot system is via /boot/firmware/cmdline.txt
  stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline_file

- name: Enable cgroup via boot commandline if not already enabled
  lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  when:
    - ansible_distribution == 'Ubuntu'


- name: Reboot to enable cgroups
  reboot:
  when:
    - ansible_distribution == 'Ubuntu'
